services:
  - type: web
    name: rustysnake-game
    env: docker
    buildCommand: "."
    dockerfile: "./rustysnake-game/Dockerfile"
    envVars:
      - key: RUST_LOG
        value: "info"
      - key: TERM
        value: "xterm-256color"
    plan: free
    numInstances: 1
    regions: ["oregon"]
    healthCheckPath: /nonexistent
    healthCheckTimeoutSeconds: 5
    healthCheckIntervalSeconds: 10
    healthCheckThreshold: 3
    autoDeploy: true
